# Generated by Django 5.0.6 on 2024-05-29 02:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Downloadable",
            fields=[
                (
                    "sno",
                    models.AutoField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("filename", models.CharField(default=None, max_length=500)),
                ("file", models.FileField(default=None, upload_to=None)),
                (
                    "file_made_available",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "downloadable",
                "verbose_name_plural": "downloadables",
            },
        ),
    ]
