# Generated by Django 5.0.6 on 2024-05-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bit_files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadable",
            name="downloadable_link",
            field=models.TextField(default=None),
        ),
    ]
