# Generated by Django 5.0.6 on 2024-05-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bit_files", "0002_downloadable_downloadable_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadable",
            name="file",
            field=models.FileField(default=None, upload_to="downloadables/"),
        ),
    ]
