# Generated by Django 5.0.6 on 2024-06-08 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalUserCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "who",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Faculty", "Faculty"),
                            ("Staff", "Staff"),
                        ],
                        max_length=30,
                    ),
                ),
                ("Emergency_id01", models.CharField(max_length=10, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("phone_alt", models.CharField(default=None, max_length=20, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                            ("Not to say", "Not to say"),
                        ],
                        max_length=30,
                    ),
                ),
                ("birth", models.DateField()),
                ("country", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("pinCode", models.CharField(max_length=6)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UserCredentials",
                "verbose_name_plural": "AdditionalUserCredentials",
            },
        ),
    ]
