# Generated by Django 5.0.6 on 2024-06-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bit_auth", "0002_alter_additionalusercredentials_who"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalusercredentials",
            name="who",
            field=models.CharField(
                choices=[
                    ("Authority", "Admin"),
                    ("Student", "Student"),
                    ("Faculty", "Faculty"),
                    ("Staff", "Staff"),
                ],
                max_length=30,
            ),
        ),
    ]
