# Generated by Django 5.0.6 on 2024-06-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bit_auth", "0003_alter_additionalusercredentials_who"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalusercredentials",
            name="phone_alt",
            field=models.CharField(default="", max_length=20, null=True),
        ),
    ]
