# Generated by Django 5.0.6 on 2024-05-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('notif_title', models.CharField(max_length=500)),
                ('notif_desc', models.CharField(max_length=1000)),
                ('notify_link', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
            },
        ),
    ]
