# Generated by Django 5.0.6 on 2024-05-28 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_bit', '0002_notification_notif_desc_dtme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField(default=None)),
                ('answer', models.TextField()),
                ('time_asked', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
