# Generated by Django 5.0.6 on 2024-06-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration_bit", "0003_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "sno",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(default=None, max_length=50)),
                ("title", models.CharField(default=None, max_length=1000)),
                ("desc", models.TextField()),
                ("slug", models.SlugField()),
                ("date_time_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
    ]
