# Generated by Django 5.0.6 on 2024-06-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration_bit", "0004_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
    ]
